### ISSUE TITLE
Editar Check individual de uma checklist resulta em Internal Server Error

### ISSUE THREAD

**Issue by davidjentjens** [marcosvporto/revisionhub#14]
Etapas para reproduzir:

- Fazer um login na aplicação
- Clicar em Minhas Listas
- Selecionar uma Checklist e clicar em Editar
- Criar um novo Check
- Salvar
- Editar esse mesmo Check
- Salvar

Possíveis motivos: 
- Botão de salvar não está mandando as requisições de atualização de Check corretamente, gerando erros internos na api

**Comment by Thlamz** [comment]
Erro consertado e deploy feito

O erro era causado pelo acúmulo de checks idênticas quando era feita uma edição, o conserto foi assegurar que toda check na lista de edição é única.
